import { useQuery } from "@tanstack/react-query";
import env from "~/config/env";
import type { paths } from "~/types/api";
import type { SuccessResponse } from "~/types/responses";

// These type declarations were generated by AI
type GetPaths = {
  [K in keyof paths]:
    paths[K] extends { get: infer G }
      ? G extends never
        ? never
        : K
      : never
}[keyof paths];

export default function useApiQuery<U extends GetPaths>(path:U, queryKey: readonly unknown[]) {
    return useQuery<SuccessResponse<paths[U]['get']>>({
        queryKey,
        queryFn: async () => {
            const response = await fetch(`${env.apiBaseUrl}${path}`)

            return await response.json()
        }
    })
}
