import { useMutation, type MutationFunction } from "@tanstack/react-query";
import env from "~/config/env";
import type { paths, components } from "~/types/api";
import type { SuccessResponse } from "~/types/responses";

// These type declarations were generated by AI
type PostPaths = {
  [K in keyof paths]:
    paths[K] extends { post: infer G }
      ? G extends never
        ? never
        : K
      : never
}[keyof paths];

export default function useCalculateLoan() {
    const path: PostPaths = '/api/loans/calculate'

    const mutationFn: MutationFunction<
        SuccessResponse<paths[PostPaths]['post']>,
        components['schemas']['LoanCalculateRequest']
    > = async body => {
        const response = await fetch(`${env.apiBaseUrl}${path}`, {
            body: JSON.stringify(body),
            method: 'post',
            headers: {
                'Content-Type': 'application/json'
            }
        })

        return await response.json()
    }
    
    return useMutation({ mutationFn })
}
