

// These type declarations were generated by AI
export type JsonResponse<T> =
  T extends { content: { 'application/json': infer R } }
    ? R
    : never

export type SuccessResponse<T> =
  T extends { responses: infer R }
    ? 200 extends keyof R
      ? JsonResponse<R[200]>
      : never
    : never
